### ISSUE TITLE
Cannot load wdc .taco in Tableau Public 2023.3.3

### ISSUE THREAD

**Issue by fcruzel** [tableau/wdc3#31]
Hi, I've trying to load a wdc v3 in Tableau Public 2023.3.3, but it doesn't appear in the connectors list. I've also tried adding it to the connectors folder and running tabpublic.exe with `-DConnectPluginsPath` flag, without success.

`taco run` only offers Tableau Desktop and Tableau Prep as options. Does that mean that Tableau Public does not offer support for the version 3.0 of the wdc? Will v2 of the wdc also stop working in the next versions of Tableau Public?

**Comment by fcruzel** [comment]
it seems that wdc3 is not supported in tableau public: https://community.tableau.com/s/question/0D58b0000C8M6BqCQK/support-for-tableauwdc-30-in-tableau-public

**Comment by irbian** [comment]
Is this planned on future versions of Tableau Public?
